start: statement+

statement: assignment
    // | if_statement
    // | loop_statement
    | function_call
    | define_statement

define_statement: "@Dim" identifier
assignment: identifier "=" expression
expression: atom (calculator atom)*
calculator: "+"
    | "-"
    | "*"
    | "/"

if_statement: "if" expression ":" statement+ ["else" ":" statement+]
// loop_statement: "for" variable "in" expression ":" statement+
function_call: identifier "(" arguments ")"
arguments: expression ("," expression)*

atom: number
    | string
    | identifier
    // | function_call


identifier: /[a-zA-Z_][a-zA-Z0-9_]*/
string: /"[^"]*"/
number: NUMBER
COMMENT: ";" /[^\n]*/

%import common.NUMBER
%import common.WS
%ignore WS
%ignore COMMENT
